name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: mbianco/ghex:gcc-9

    steps:
      - uses: actions/checkout@v1
      - name: Configure
        run: |
          mkdir -p build && cd build
          cmake .. -DGHEX_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build --parallel 2
      - name: Execute tests
        run: cd build && ctest --output-on-failure	
